#pragma config(Sensor, dgtl1,  count,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  call0,          sensorTouch)
#pragma config(Sensor, dgtl4,  call1,          sensorTouch)
#pragma config(Sensor, dgtl5,  call2,          sensorTouch)
#pragma config(Sensor, dgtl7,  ind0,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  ind1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  ind2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, resetSw,         sensorTouch)
#pragma config(Motor,  port1,           driver,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// contains the current floor.
int current = 0;

int floorDelay = 5000;
int resetDelay = 12000;

// these are the vaules of the encoder for each floor.
// they can also be found using calibrate()
int floors[3] = {74, 258, 454};

int lifecycle(bool isMoving);

#include "utilities.c"
#include "indicators.c"
#include "control.c"
#include "motion.c"

task main() {
  doReset();

  int next;

  while (1) {
    if (lifecycle(false)) {
      dequeue(current);
      while (queue[0] || queue[1] || queue[2]) {
        next = getNextTarget(current);
        if (~next) {
          indMode[current] = 0;
          current = next;
          goToFloor(next);
          clearTimer(0);
          while (time1[0] < floorDelay) {
            lifecycle(false);
          }
        }
      }
    }
    if ((time1[0] > floorDelay) && current) {
    	goToFloor(0);
      current = 0;
    }
  }

}

int lifecycle(bool isMoving) {
  doIndicateTick();
  int ret = 0;
  // queue floors for any buttons pressed
  if (SensorValue[call0]) {
    ret++;
    queue[0] = true;
    indMode[0] = 4;
  }
  if (SensorValue[call1]) {
    ret++;
    queue[1] = true;
    indMode[1] = 4;
  }
  if (SensorValue[call2]) {
    ret++;
    queue[2] = true;
    indMode[2] = 4;
  }
  // if the reset button is pressed, do a reset only. if the three buttons are also pressed, calibrate.
  if (SensorValue[resetSw]) {
    indMode[0] = indMode[1] = indMode[2] = 2;
    while (SensorValue[resetSw]) {
      doIndicateTick();
    }
    doReset();
    current = 0;
  }
  return ret;
}
