#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           motorRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motorLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           motorServo,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Activity 3.1.3 Basic Inputs Programming
Team Members: DeShawn Turner, Jordan Yoon-Buck
Date: February 21, 2017
Section: POE B1
*/

void waitUntilFar(int distance) {
	while(true) {
		if (SensorValue[sonar] != -1) {
		  if (SensorValue[sonar] > distance) {
		  	wait(0.15);
		  	if (SensorValue[sonar] > distance) break;
		  }
		}
	}
}

task main() {
	untilSonarLessThan(20, sonar);						// wait until an object is closer than 20 cm
	startMotor(motorLeft, 63);								// start both motors
	startMotor(motorRight, 63);
	waitUntilFar(25);													// wait until the object moves farther than 25 cm
	motor[motorLeft] = motor[motorRight] = 0; // turn both motors off
	turnLEDOn(green);												  // turn the LED on for 6.25
	wait(6.25);
	turnLEDOff(green);
}
