#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           motorRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motorLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           motorServo,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Activity 3.1.2 Basic Outputs Programming
Team Members: DeShawn Turner, Jordan Yoon-Buck
Date: February 21, 2017
Section: POE B1
Task Description:
Pseudocode:

*/


task main() {
	untilPotentiometerLessThan(2048, potentiometer);		// Verify that the potentiometer is at a value of less than 2048.
	turnLEDOn(green);																		// Turn on the greenLED
	wait(0.25);
	untilPotentiometerGreaterThan(2048, potentiometer); // until the potentiometer is at a value greater than 2048.
	turnLEDOff(green);																	// Turn off the greenLED.
	motor[motorLeft] = 63;															// Turn on the leftMotor at half power
	wait(0.25);
	untilPotentiometerLessThan(2048, potentiometer);		// until the potentiometer is at a value of less than 2048.
	motor[motorLeft] = 0;																// Turn leftMotor off.
}
